print("CHƯƠNG TRÌNH KIỂM TRA KẾT QUẢ BOOLEAN EXPRESSION")
x = int(input("Nhập giá trị x: "))
y = int(input("Nhập giá trị y: "))
Z = int(input("Nhập giá trị z: "))

print("a) x == 3:", x == 3)
print("b) x < y:", x < y)
print("c) x >= y:", x >= y)
print("d) x <= y:", x <= y)
print("e) x != y - 2:", x != y - 2)
print("f) x < 10:", x < 10)
print("g) x >= 0 and x < 10:", x >= 0 and x < 10)
print("h) x < 0 and x < 10:", x < 0 and x < 10)
print("i) x >= 0 and x < 2:", x >= 0 and x < 2)
print("j) x < 0 or x < 10:", x < 0 or x < 10)
print("k) x > 0 or x < 10:", x > 0 or x < 10)
print("l) x < 0 or x > 10:", x < 0 or x > 10)
